import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Disclaimer } from './components/CookieManager'
import { ContextProviders } from './components/Contexts'
import './globals.css'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900'
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<ContextProviders>
				<body className={`${geistSans.variable} ${geistMono.variable}`}>
					{children}
					<Disclaimer />
				</body>
			</ContextProviders>
		</html>
	)
}
