name: Check linter in PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # pin@v4.0.0

      - name: Install Nodejs
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin@v4.0.2
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install modules
        run: pnpm i
      - name: Run Prettier ESLint check
        run: pnpm lint
